name: Build ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Arch ISO
        run: |
          docker run --rm \
            --privileged \
            -v "$PWD:/workspace" \
            -w /workspace \
            archlinux:latest \
            bash -c '
              pacman -Sy --noconfirm archiso &&
              mkdir -p work out &&
              mkarchiso -v -w work -o out .
            '

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: Lowsys-Linux-ISO
          path: out/*.iso
